default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/dummy_dev.sqlite3

test:
  <<: *default
  database: db/dummy_test.sqlite3

production:
  <<: *default
  database: db/dummy.sqlite3
